### ISSUE TITLE
Can't recognize the /metrics outputs

### ISSUE THREAD

**Issue by KyleGobel** [phnx47/Prometheus.Client#2]
Hey,

I've been trying for a couple hours now.

Everything looks good at /metrics from what I can tell, but i've been getting strange errors from prometheus.

When in protobuf mode there error switches between these two:
![image](https://user-images.githubusercontent.com/4460054/28900632-95340222-77c0-11e7-976a-5e09a4f4c88a.png)

and 
![image](https://user-images.githubusercontent.com/4460054/28900641-ac1d8738-77c0-11e7-998b-f41b35e7b8fd.png)

I've forced the controller (tried with some middleware I wrote to handle the /metrics endpoint, and also been trying with your controller in the aspnetcore example) to just run in text mode by passing the ``ScrapeHandler.GetContentType(null)``, in which case I then get a different error.

![image](https://user-images.githubusercontent.com/4460054/28900682-0b2a100c-77c1-11e7-90be-aa32596d4095.png)

From what I can tell, the output of my ``/metrics`` endpoint is valid and correct?  Here's the output I see in the browser when navigating there

```
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds
# TYPE process_cpu_seconds_total COUNTER
process_cpu_seconds_total 2.125
# HELP dotnet_collection_count_total GC collection count
# TYPE dotnet_collection_count_total COUNTER
dotnet_collection_count_total{generation="0"} 0
dotnet_collection_count_total{generation="1"} 0
dotnet_collection_count_total{generation="2"} 0
# HELP dotnet_collection_errors_total Total number of errors that occured during collections
# TYPE dotnet_collection_errors_total COUNTER
# HELP dotnet_totalmemory Total known allocated memory
# TYPE dotnet_totalmemory GAUGE
dotnet_totalmemory 11878696
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds
# TYPE process_start_time_seconds GAUGE
process_start_time_seconds 1501719306.97944
```

I've been trying this on my kubernetes cluster, and also locally on my windows 10 machine.

Any ideas what I'm doing wrong?

**Comment by KyleGobel** [comment]
Ok, after forever I got at least the plain text version working by removing the byte order mark.

```
content = content.Trim(new char[] {'\uFEFF', '\u200B'});
```

**Comment by phnx47** [comment]
It's like a bug. I'll try to fix it.

**Comment by phnx47** [comment]
Sorry for long answer.

I found an error in my example with Encoding

**Comment by phnx47** [comment]
Trouble with Controllers. I'm looking for a solution

Use
https://github.com/phnx47/Prometheus.Client.Owin
or
https://github.com/phnx47/Prometheus.Client.MetricServer

**Comment by phnx47** [comment]
I fixed examples.

@KyleGobel can you check?
