### ISSUE TITLE
[MetricServer, Bug] MetricServer crashes entire process if port taken by another app

### ISSUE THREAD

**Issue by ig-sinicyn** [phnx47/Prometheus.Client#3]
**Repro:** run an app with this code twice:
```cs
		static void Main(string[] args)
		{
			var metricServer = new MetricServer("localhost", 50800);
			metricServer.Start();
			Console.ReadKey();
		}
```

**Expected behavior:** On a second instance, metricServer.Start() throws an exception (or some event fired, or the Start() method returns false, anything but killing the process will do:) )

**Actual behavior:** Unhandled exception is thrown, entire process crashes.

**Reason:** the [StartListen](https://github.com/phnx47/Prometheus.Client.MetricServer/blob/master/src/Prometheus.Client.MetricServer/MetricServer.HttpListener.cs#L76) body was not wrapped with try...catch.

**Comment by AlexeyUsachev** [comment]
What can I do to make this pull request merge faster?

**Comment by phnx47** [comment]
You can do PR or wait when I release on January

**Comment by phnx47** [comment]
I released new version and solved this
