### ISSUE TITLE
AsciiFormatter is incompatible with 2.0 release of prometheus

### ISSUE THREAD

**Issue by coding4food** [phnx47/Prometheus.Client#4]
As new version of Prometheus scrapes metrics only in text format, it cannot parse output of `AsciiFormatter` with UTF-8 BOM. Original `prometheus-net` formatter uses `UTF8Encoding` without BOM (https://github.com/andrasm/prometheus-net/blob/2da8ab9ec225bbcb0fa9b088ff3d09725d23b405/prometheus-net/Internal/AsciiFormatter.cs#L14).

**Comment by phnx47** [comment]
Thanks! Fixed in 1.2.2
