### ISSUE TITLE
Guidance on using metrics

### ISSUE THREAD

**Issue by tomkerkhove** [phnx47/Prometheus.Client#7]
Can you please provide some guidance on how to use the metrics if your not using `ScrapeHandler`?

`UsePrometheusServer` does not exist and individual snippets are not being tracked in Prometheus:
```
var gauge = Metrics.CreateGauge("gauge", "help text");
gauge.Inc(3.4);
gauge.Dec(2.1);
gauge.Set(5.3);
```

**Comment by phnx47** [comment]
I don't understand the problem.

**Comment by phnx47** [comment]
```UsePrometheusServer``` in https://github.com/phnx47/Prometheus.Client.Owin

**Comment by tomkerkhove** [comment]
Ok that's the problem, it is mentioning parts of a different repo & package.

So if I use the prometheus server it will scrape the metrics from my gauge automatically then or? Do you support using a pushgateway as well?

**Comment by phnx47** [comment]
Yes, automatically.

Pushgateway will be done later

**Comment by tomkerkhove** [comment]
It's up and running, thank you!
